### ISSUE TITLE
Validation of TOTP always false when adding custom period

### ISSUE THREAD

**Issue by baartch** [PlanetHoster/time2fa#301]
Hi

I wanted to use your package. But I face an issue.

I tried to following to create a TOTP
```typescript
  // Generate the OTP
  const config = generateConfig({
    period: 120,
  });
  const secret = generateSecret(config.secretSize);
  const codes = Totp.generatePasscodes({ secret: secret }, config);
```

and the following to validate (of course with passcode and secret from above)
```typescript
  // Validate the OTP
  const config = generateConfig({
    period: 120,
  });
  const valid = Totp.validate({ passcode: '097991', secret: '2X4A3XCNPJJSHU4O' }, config);
```

This always results in `false`. When I remove the `period: 120` in the config, it works.
Any idea? Is there a limit for the _period_?

**Comment by hugoewarrior** [comment]
Hi, i recently saw a PR fixing this. Basically you should add the same config values on `Totp.validate` function. Example: 
![image](https://github.com/user-attachments/assets/c1701f1e-2253-4984-8d6f-7e46a753d67b)

Hope it helps!
