### ISSUE TITLE
 Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by MrRainesE** [PlanetHoster/time2fa#33]
Getting this error with:
```
"react": "^17.0.2",
"react-dom": "^17.0.2",
"react-scripts": "^5.0.1",
```
![image](https://github.com/PlanetHoster/time2fa/assets/76207902/a2eec257-29b3-4133-8b30-e761c29d28c3)i already tried adding  the packages below to the dependencies in the package.json but then i get a different error
```
"crypto":"npm:crypto-browserify",
"stream":"npm:stream-browserify",
"buffer":"npm:buffer"
```
![image](https://github.com/PlanetHoster/time2fa/assets/76207902/51c19553-1a4e-4a9f-a7c0-531b0fb97462)

**Comment by MarcAndreG** [comment]
HI did you try the solution in the error?

![Screen Shot 2023-05-19 at 8 32 56 AM](https://github.com/PlanetHoster/time2fa/assets/13788169/426466dd-33d7-485a-bb33-275723209a8f)

**Comment by MarcAndreG** [comment]
I think the problem is you try to run the package in the browser.

Did you try to add this to the package.json ?

`
"browser": {
    "crypto": false
}
`

**Comment by MrRainesE** [comment]
@MarcAndreG  Yes i tried adding that to th epackage.json but did not work. Just solved this with this: https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined
```
 "scripts": {
    "debug": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
  },
```
Create a file config-overrides.js in the root folder (NOT under src, in the same folder like your package.json) and paste the following code inside:
```
const webpack = require("webpack")

module.exports = function override(config, env) {
    //do stuff with the webpack config...
    config.resolve.fallback = {
        ...config.resolve.fallback,
        stream: require.resolve("stream-browserify"),
        buffer: require.resolve("buffer"),
    }
    config.resolve.extensions = [...config.resolve.extensions, ".ts", ".js"]
    config.plugins = [
        ...config.plugins,
        new webpack.ProvidePlugin({
            process: "process/browser",
            Buffer: ["buffer", "Buffer"],
        }),
    ]
    // console.log(config.resolve)
    // console.log(config.plugins)

    return config
}

```
