### ISSUE TITLE
user object is missing in the generateUrl

### ISSUE THREAD

**Issue by MrRainesE** [PlanetHoster/time2fa#34]
```
 const config = { algo: "sha1", digits: 6, period: 30, secretSize: 10 };
 const secret = "F5LE3AAKV7OD264A";
```
```
console.log(generateUrl(
      {
        issuer: "N0C",
        user: "johndoe@n0c.com",
        secret: secret
      },
      config
    ));

// result: https://totp/?issuer=N0C&period=30&secret=F5LE3AAKV7OD264A
```

**Comment by MrRainesE** [comment]
Windows 10. Hereby a codesandbox https://codesandbox.io/s/staging-snow-0lm3po?file=/src/App.js

**Comment by MarcAndreG** [comment]
Did you find any answer to your problem?

**Comment by MrRainesE** [comment]
@MarcAndreG No,user object is still missing **otpauth://totp?issuer=N0C&period=30&secret=ABCDEFGHIJKLMN12**

in your the example
`otpauth://totp/N0C:johndoe%40n0c.com?issuer=N0C&period=30&secret=ABCDEFGHIJKLMN12`
