### ISSUE TITLE
Validating passcode evaluates to false

### ISSUE THREAD

**Issue by MikeTeddyOmondi** [PlanetHoster/time2fa#39]
When generating a new TOTP is successful:

```js
      const config = generateConfig({
        digits: 6,
        period: 30,
        algo: "sha256",
        secretSize: 10,
      });

      const secret = TOTP_SECRET; // from ENV variable;
      const codes = Totp.generatePasscodes({ secret }, config);
      const totp = codes[0];
```

But when validating the just newly created TOTP it evaluates to false:

```js
    const { totp } = req.body;
    const secret = TOTP_SECRET; // from ENV variable

    const config = {
      digits: 6,
      period: 30,
      algo: "sha256",
      secretSize: 10,
    };

    const isValid = Totp.validate(
      {
        passcode: totp,
        secret: secret,
      },
      config
    );
    console.log({ isValid }); // Evaluates to false when the totp is valid
```

What could be wrong with my code?

**Comment by MarcAndreG** [comment]
Hi,

Thanks for reporting an issue.

Just to make sure the problem not coming from the secret itself can you show me how did you generate the secret ?

Thank you !

**Comment by MikeTeddyOmondi** [comment]
@MarcAndreG I used the generateSecret() function provided then added it to the .env file

**Comment by MarcAndreG** [comment]
Yes you need to use the same secret to validate.

**Comment by MikeTeddyOmondi** [comment]
I am still using the same secret as shown above in the code. under secret key and value
